- daal4py/pca.py
- native/common.hpp
- native/npyfile.h
- native/pca_bench.cpp
- sklearn/pca.py
This PR adds PCA benchmarks and NPY output for PCA.
Benchmarks support `svd_solver`s `daal` and `full`. They were verified against scikit-learn PCA using the NPY serialization.
> Add PCA benchmarks

- Makefile
- README.md
- sklearn/args.py
- sklearn/log_reg.py
- sklearn/svm_bench.py
@oleksandr-pavlyk 
This PR attempts to make the benchmarks easier to run and aggregate.
- Separate out sizes for different benchmarks
- Output number of threads in sklearn runs
- Refactor makefile to
- allow executing specific benchmarks only
- output to files in `output/<impl>/<bench>.out`
> Refactor makefile

- Makefile
- daal4py/df_clsf.py
- daal4py/df_regr.py
- native/decision_forest_clsf_bench.cpp
- native/decision_forest_regr_bench.cpp
- Add benchmarks for daal4py random forest
- Native random forests: Use MT2203 engine for fit and single precision float for prediction for consistency with sklearn.
> Add benchmarks for daal4py random forest, fix native RF benches for consistency

- daal4py/log_reg.py
This PR adds logistic regression replicating the results of `sklearn.linear_model.LogisticRegression` but implemented in daal4py. It supports solvers `lbfgs` and `newton-cg`. `test_fit` uses the canonical form of logistic regression for the binary case (which in scikit-learn is `multi_class='ovr'`) and the multinomial (softmax of exponentiated scores, `multi_class='multinomial'`) for the multi-class case. `test_predict` supports any combination of `n_classes` and `multi_class`, but we use the same `multi_class` used in `test_fit`.
While we cannot directly use daal4py's logistic regression because it isn't as easy as native DAAL to pass in a custom solver (see #8), we use daal4py's logistic regression objective functions and math primitives to compute logistic regression.
> Add daal4py logistic regression benchmark

- Makefile
Running "make python" results in make error:
`make: *** No rule to make target 'data/', needed by 'data/kmeans_1000000x50.npy'.  Stop.`
Changes in this pull request repair Makefile by adding subdirectory for clustering data.
> Fix kmeans data generation error in Makefile

- daal4py/dbscan.py
- native/Makefile
- native/common.hpp
- native/dbscan_bench.cpp
- sklearn/bench.py
- sklearn/dbscan.py
@oleksandr-pavlyk 
This PR adds native, sklearn, and daal4py implementations of DBSCAN benchmarks, usable with kmeans clustering data when given epsilon=10.
> Add DBSCAN benchmarks

- config_example.json
- cuml/train_test_split.py
- sklearn/train_test_split.py
Benchmarks for scikit-learn and cuml implementation of train_test_split function.
Scikit-learn API reference: https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html
> Train test split benchmarks

- configs/cuml_config.json
- datasets/load_datasets.py
- datasets/loader.py
- runner.py
1. Returned support of hardware and software for the logging.
2. Extend cuml config for `skin_segmentation` workload
3. Add loader for `codrnanorm` dataset
> Small extensions & add new dataset

- bench.py
- utils.py
- `device` keyword added to the report of each benchmark to recognize which device was used
- Intel GPU hardware information included in the report if such GPU exists on the system
Example of result.json:
hardware section
``` json
"GPU Intel #1": {
"Type": "GPU",
"Profile": "FULL_PROFILE",
"Version": "OpenCL 3.0 NEO",
"Name": "Intel(R) Iris(TM) Pro Graphics P580 [0x193a]",
"Vendor": "Intel(R) Corporation",
"C version": "OpenCL C 3.0",
"Driver version": "21.13.1943"
}
```
example of benchmark output:
``` json
{
"library": "sklearn",
"algorithm": "kmeans",
"stage": "training",
"device": "gpu",
"input_data": {
"data_format": "pandas",
"data_order": "F",
"data_type": "float64",
"dataset_name": "synthetic_blobs",
"rows": 1000000,
"columns": 50,
"n_clusters": 10
},
"algorithm_parameters": { …
```
> Add device information in the report json file

- cuml_bench/df_clsf.py
- cuml_bench/df_regr.py
`min_rows_per_node` cuML Random Forest parameter was renamed to `min_samples_split`: [API link](https://docs.rapids.ai/api/cuml/stable/api.html#random-forest). It wasn't changed in benchmarks and leads to error while running.
> Fix missing cuML Random Forest parameter

- azure-pipelines.yml
- bench.py
- daal4py_bench/distances.py
- daal4py_bench/requirements.txt
- datasets/loader_utils.py
- runner.py
- sklearn_bench/requirements.txt
- sklearn_bench/tsne.py
- utils.py
- xgboost_bench/requirements.txt
Addresses most issues in #95
- Fixed 2 instances of unnecessary else
- Fixed 2 instances of using range(len(...))
- Fixed 1 instance of code complexity by removing unnecessary "is not None" check
- Fixed 1 instance of code security by using requests.get instead of urllib.request.urlretrieve
There is still 1 instance of code complexity issue remaining. I have performed some minor refactoring, but it's still too complex according to codefactor.io.
> Refactor code

- bench.py
- configs/skl_xpu_config.json
- runner.py
Add parameters to runner.py that define devices and data types available to run
Unselected devices and data types will be ignored in configs
for example if config contains
`device: ["host", "gpu",  "cpu"]`
and you run
`python runner.py --devices cpu gpu`
cpu and gpu cases will be launched,
but if config contains:
`device: ["host", "gpu"]`
and you run 
`python runner.py --devices cpu gpu`
only  gpu case will be launched 
default values ​​do not limit the available devices and data types
> Add available devices and dtypes selection to runner.py

- report_generator/xpu_report_gen_config.json
- runner.py
Add option for report config selection
If report flag is not set, report generator will not be launched
If no config specified default config will be used
`python runner.py --report`
(launch report with default config)
`python runner.py --report report_generator/myconf.json`
(launch report with  custom config)
Added more detailed config for new benchmark cases
> Report config selector

- modelbuilders_bench/lgbm_mb.py
- modelbuilders_bench/xgb_mb.py
Nan values are not supported for model builders yet. However, no internal checks are not implemented. Checks in the benchmarks looks like a possible intermediate solution.
> Adding check for nan values

- modelbuilders_bench/mb_utils.py
np.float is [depricated](https://numpy.org/doc/stable/release/1.24.0-notes.html#expired-deprecations) in numpy 1.24
> np.float is depricated in numpy 1.24

- configs/regular/kmeans.json
- For kmeans++, the default n_init=1 https://github.com/scikit-learn/scikit-learn/blob/main/sklearn/cluster/_kmeans.py#L346. Probably makes sense to benchmark the default behavior.
> update n_init for kmeans

- configs/regular/pca.json
- envs/conda-env-sklearn.yml
- envs/requirements-sklearn.txt
Update `svd_solver=covariance_eigh` in PCA config to reflect [sklearn 1.5](https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.PCA.html#pca) and related [sklearnex patching](https://github.com/intel/scikit-learn-intelex/commit/ba8206df0260c19cb2759702b318d5067c56c888#diff-9624711e0882a1b18ec37e33bbe526d4889c4d2f699a48cdf54f8a9c343cd0e3R230) changes.
Remove `sklearn<1.5` limitation.
> Update solver in PCA config

- sklbench/report/implementation.py
Fix for summary page without index: move it from last place to first in workbook.
> Move summary sheet to first place in report

- README.md
- sklbench/datasets/README.md
- sklbench/datasets/__init__.py
- sklbench/datasets/loaders.py
Changes:
- Add support of user-provided datasets in sklbench cache-compatible format
- Add documentation to describe this feature [(link)](https://github.com/Alexsandruss/scikit-learn_bench/blob/dev/custom-dataset-spec/sklbench/datasets/README.md#how-to-modify-dataset-for-compatibility-with-scikit-learn_bench)
> Support of user-provided datasets

- .github/pull_request_template.md
- .github/workflows/pr-checklist.yml
Sync from sklearnex and oneDAL with performance section removed.
_Add a comprehensive description of proposed changes_
_List associated issue number(s) if exist(s): #6 (for example)_
_Documentation PR (if needed): #1340 (for example)_
---
PR should start as a draft, then move to ready for review state after CI is passed and all applicable checkboxes are closed.
This approach ensures that reviewers don't spend extra time asking for regular requirements.
You can remove a checkbox as not applicable only if it doesn't relate to this PR in any way.
Checklist to comply with **before moving PR from draft**:
**Testing**
> Update PR template and add checklist workflow

- sklbench/utils/common.py
This PR fixes an issue in which the logic here would assume that JSON outputs from `conda list` would always have an empty line at the end, which is not necessarily the case depending on versions and shell nuances.
Checklist to comply with **before moving PR from draft**:
**Testing**
> FIX: Don't error out when JSON doesn't end with empty line

- .pre-commit-config.yaml
- azure-pipelines.yml
Align CI linter config with scikit-learn-intelex repo.
---
PR should start as a draft, then move to ready for review state after CI is passed and all applicable checkboxes are closed.
This approach ensures that reviewers don't spend extra time asking for regular requirements.
You can remove a checkbox as not applicable only if it doesn't relate to this PR in any way.
Checklist to comply with **before moving PR from draft**:
**Testing**
> Update CI linter config

- sklbench/report/implementation.py
Usage of `==` operator for `indifferent` metric type led to errors due to unequal indices of compared data frames in some cases. pd.DataFrame's method `eq` handles these cases and assigns values correctly.
---
**Testing**
> Fix comparison for `indifferent` metric type in report

- configs/README.md
- configs/regular/bf16/knn.json
- configs/regular/bf16/pca.json
- configs/spmd/large_scale/logreg_strong.json
- sklbench/benchmarks/sklearn_estimator.py
- sklbench/report/implementation.py
Merging incremental logic updates here instead of main branch. This supports ability for user to run incremental algos on a dataset larger than memory by running on batches of the same dataset, required to produce submitted results.
Additionally some minor tweaks to configs and scripts to align reproducer results to report. Includes:
- fixed logreg strong config error
---
PR should start as a draft, then move to ready for review state after CI is passed and all applicable checkboxes are closed.
This approach ensures that reviewers don't spend extra time asking for regular requirements.
You can remove a checkbox as not applicable only if it doesn't relate to this PR in any way.
Checklist to comply with **before moving PR from draft**:
**Testing**
> Support incremental benchmarking of datasets larger than memory + final config/logic alignment
